### ISSUE TITLE
complete, browser based example?

### ISSUE THREAD

**Issue by akosmaroy** [pouchdb/geopouch#11]
I wonder if there is a complete, browser based example on how tou use GeoPouch, that would demonstrate:

* how to include GeoPouch in a browser-based JavaScript environment
* how to add a geo-referenced document
* how to retrieve geo-referenced documents

**Comment by scubbx** [comment]
Did anyone ever succeed in using GeoPouch in a browser? I also still am not able to get it running?

**Comment by marten-de-vries** [comment]
I did succeed in using GeoPouch in a browser-like environment, but that's quite a long time ago. No idea if it would still work. Anyway, I used [browserify](http://browserify.org/), and this pretty much was my source file: https://git.launchpad.net/python-pouchdb/tree/js/python-pouchdb-js/index.js#n52 .

As for querying, did you look at the test suite for examples? https://github.com/pouchdb/geopouch/blob/master/test/test.js

Hope that helps.

**Comment by scubbx** [comment]
Thanks for the hints!
I'm not even getting to the query part, since the geopouch library does not even attach to any PouchDB database. I'm able to call a "geopouch" object at the root level.
I tried browserify and webpack on the dist-version and on the source version. If I use these versions, already the ``PouchDB.plugin('Spatial',geopouch);`` command fails.
Sadly, I'm far from being an expert with browserify and the likes of ...

**Comment by calvinmetcalf** [comment]
if you include the dist version via a script tag that would be when you'd then do PouchDB.plugin('Spatial',geopouch);

**Comment by scubbx** [comment]
The suspicious thing for me is, that the call ``PouchDB.plugin('Spatial',gepouch);`` does return a function.

To clearly state my proceeding:

My HTML file looks like this:

![pdbspatialquestion1](https://cloud.githubusercontent.com/assets/1347421/12419599/799ff53e-beb7-11e5-963a-26e2dfca7ea7.png)


To visualize the feedback, I excluded any scripts from this code but entered them in the JS console of the browser:

![pdbspatialquestion](https://cloud.githubusercontent.com/assets/1347421/12419527/02fba9fa-beb7-11e5-8326-74bd3faf71cd.png)

When I do not use the downloaded version of geopouch, but a browserified one, a message after the command ``PouchDB.plugin('Spatial',gepouch);`` is displayed, saying ``Uncaught ReferenceError: geopouch is not defined(…)'``.

I hope this is not due to some misunderstanding or technical shortcoming on my part ... ? Or better: I hope it is! :-)

**Comment by calvinmetcalf** [comment]
sorry, the syntax should actually be `PouchDB.plugin(geopouch)`

**Comment by scubbx** [comment]
This works, the library is loaded and attached to any PouchDB ! :-D
But.... while the same query produces results on a CouchDB via its native HTTP API, it does not give any results via PouchDB. Neither on the replicated version of the CouchDB nor on the CouchDB accessed by the PouchDB interface. The query and result via PouchDB look like this:

![pdbspatialquestion2](https://cloud.githubusercontent.com/assets/1347421/12425633/06c81c16-bed6-11e5-93c1-a0b9bcf7893d.png)

Using the rtree branch makes no difference.

The results via the CouchDB API look like this:

![pdbspatialquestion3](https://cloud.githubusercontent.com/assets/1347421/12425750/94b85d24-bed6-11e5-9d75-59c12eb3f1bb.png)

**Comment by vmx** [comment]
@scubbx Try `[[0, 180], [0, 90]]` instead.

**Comment by scubbx** [comment]
*haha* Right!

But nontheless:
![pdbspatialquestion4](https://cloud.githubusercontent.com/assets/1347421/12428004/9a31770c-bee2-11e5-9e5b-e4bcd7e5918d.png)

``docdb`` is the CouchDB via PouchDB interface, ``localdocdb`` is the replicated version.

Both databases are filled:

![pdbspatialquestion5](https://cloud.githubusercontent.com/assets/1347421/12428428/c52b615a-bee4-11e5-8e06-f82c2dc9d806.png)

**Comment by calvinmetcalf** [comment]
ok this is a different error, can you post graph/roads?

**Comment by scubbx** [comment]
I took a screenshot, since it has nice code-highliting:

![pdbspatialquestion6](https://cloud.githubusercontent.com/assets/1347421/12429475/b7cc2a48-beea-11e5-95e8-a26e12b4ca10.png)

Except for the design document, all documents have the ``entrytype`` property set to ``link``.

One typical document looks like this:

![pdbspatialquestion7](https://cloud.githubusercontent.com/assets/1347421/12429519/fc5cfa84-beea-11e5-9c99-e52a31348471.png)

**Comment by calvinmetcalf** [comment]
can you add a `catch(function (err){console.log(err)})` to the end of the chain?

**Comment by scubbx** [comment]
This does not give more information. Did I use it correctly?

![pdbspatialquestion8](https://cloud.githubusercontent.com/assets/1347421/12483731/fa67040a-c056-11e5-8bcc-9a50354ec3bd.png)

**Comment by calvinmetcalf** [comment]
instead of `{limit: 5}, function (resul...` you should do `{limit: 5}).then(function(resul...`

also limit isn't a supported option

**Comment by scubbx** [comment]
``localdocdb.spatial('graph/roads', [[0, 180], [0, 90]]).then( function(resul){console.log(resul);} ).catch(function (err){console.log(err)});`` and the same on ``docdb.spatial`` did not change anything.

**Comment by calvinmetcalf** [comment]
it looks like there are 2 errors that top one of the property '0' of undefined, does that have a stack trace?

**Comment by scubbx** [comment]
This one?
![pdbspatialquestion9](https://cloud.githubusercontent.com/assets/1347421/12484411/81092896-c05a-11e5-9b7c-339fb219edbd.png)

**Comment by calvinmetcalf** [comment]
ahaha looks like an invalid geometry, try doing pause on uncaught exception (or caught if that doesn't catch anything)

**Comment by beckerIGG** [comment]
Hi,
i also tried to get some geojson features out of the pouchdb. geopouch is working, but i cannot get the features out of it. I use coudb (without spatial) to store the docs and then replicate to pouch with spatial plugin. I use:
`evt_db.spatial(function (doc) {emit(doc.geometry);}, [0, 180, 0, 90]).then(function(result){
	console.log(result)}).catch(function (err){console.log(err)});`
but receive:

Possibly unhandled Error. can't delete it if there is nothing in the tree     geopouch.js (Zeile 171
a typical feature looks like that:
![feature](https://cloud.githubusercontent.com/assets/7497356/12809420/31794a48-cb1f-11e5-9ea2-66df7121953d.png)

What am i doing wrong? are the features defined correctly?

**Comment by calvinmetcalf** [comment]
ok I think there might be a bug related to replication and or error catching, I will investigate further

**Comment by beckerIGG** [comment]
Hi,
thx for keeping in touch. I broke it down to the following. If i load two json files directly into pouchdb (via bulkDocs() it works, but only for the very first time. afterwards it does not work until i delete the database manually.
`evt_db.bulkDocs([{
	"_id" : "eb46c0cc24eabb6427af7eac2b0012ac",
	"geometry" : {
		"type" : "Point",
		"coordinates" : [13.3971420055456, 52.5296601136334]
	}
}, {
	"_id" : "eb46c0cc24eabb6427af7eac2b001c9f",
	"geometry" : {
		"type" : "Point",
		"coordinates" : [13.6384082053328, 52.418740058446]
	}
}]);

//evt_db.replicate.from(evt_remoteCouch);

evt_db.spatial(
	function(doc){
		emit(doc.geometry);}
		, [[13.3971420055456,52.418740058446],[13.6384082053328,52.5296601136334]]).then(function(resp) {
	resp.length.should.equal(2);
	console.log(resp);
          var nr = resp.map(function(i) {
          	console.log(i);
            return i.properties;
          });
          nr.sort();
}).catch(function(err) {
	console.log(err)
});`
The result is:
![first_try](https://cloud.githubusercontent.com/assets/7497356/12880965/3f14e8c2-ce46-11e5-9268-d3aa04b6763a.png)
Reloading the page produces the following message (if i comment out the bulkDocs(), since everything should be inside Pouch):
![second_try](https://cloud.githubusercontent.com/assets/7497356/12881068/f9ea0d8a-ce46-11e5-8e5d-6241e4456dd1.png)

Any ideas or hints? i am not specialist in Javascript, but i need some help. Also i just get back the id. How can i get the properties of my json objects? because emit just allows to give back the geometry property.

THX in advance for any advice ot help

**Comment by calvinmetcalf** [comment]
ok I'll look into it when I get a chance

**Comment by calvinmetcalf** [comment]
ok figured it out, there was something wonky in how i was handling temp views, temp ones should now actually be temp in version 2.0.1

**Comment by calvinmetcalf** [comment]
closing this issue as it somewhat meandered into something new, if there are still problems with the indexing lets start a new issue

**Comment by akosmaroy** [comment]
thus, is there a complete, browser based example somewhere? :)

**Comment by calvinmetcalf** [comment]
no but we went over all of your questions in this thread I'm pretty sure, if there are things still stumping you ...

**Comment by scubbx** [comment]
Thank you for the hints! The examples given on the GeoCouch repository description are working, my big database is not. I will report back when I found the problem.

**Comment by ryadiv** [comment]
@akosmaroy any luck finding an example ?

**Comment by akosmaroy** [comment]
@ryadiv nope :(
